# Use the official Microsoft SQL Server
FROM mcr.microsoft.com/mssql/server:2022-latest

# Receive args from compose
ARG ACCEPT_EULA
ARG MSSQL_SA_PASSWORD

# Set the environment variables
ENV ACCEPT_EULA=${ACCEPT_EULA}
ENV MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
ENV MSSQL_PID=Express

# Create directory for data, backups, and logs
RUN mkdir -p /var/opt/mssql/data /var/opt/mssql/backup /var/opt/mssql/log

# Change the user to run sudo commands
USER root

# Change ownership of directories
RUN chown -R 10001:10001 /var/opt/mssql

# Switch back to non-root user
USER mssql

# Put the init.sql to change password and disable check policy
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the SQL Server port
EXPOSE 1433